title: Kuro的回忆档案馆
description: 这里存放了Kuro Zim的过往作品。
theme: just-the-docs

url: 

logo: "/assets/images/Head1.png"

color_scheme: zim

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'
  
mermaid:
  version: "9.1.3"

nav_enabled: true
nav_sort: default

heading_anchors: true

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "返回页顶"

collections:
  works:
    output: true
    permalink: /:collection/:path/
  coworks:
    output: true
    permalink: /:collection/:path/
  reworks:
    output: true
    permalink: /:collection/:path/
  plays:
    output: true
    permalink: /:collection/:path/
  articles:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
    
just_the_docs:
  collections:
    works:
      name: 个人原创曲
      nav_fold: true
    coworks:
      name: 合作原创曲
      nav_fold: true
    reworks:
      name: 改编与Remix
      nav_fold: true
    plays:
      name: 填词二创
      nav_fold: true
    articles:
      name: 文字
      nav_fold: true
    others:
      name: 其他
      nav_fold: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: 提示
    color: blue
  new:
    title: 更新！
    color: green
  note:
    title: 说明
    color: purple
  warning:
    title: 高能预警
    color: red

aux_links:
  "主站点":
    - "https://kurozim26.github.io/"